### ISSUE TITLE
Add `imported: true` to mutable data on imported nodes

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/inventoryware#68]
Currently we add `imported: false` on any nodes created without `parse` however there is no flag added to imported nodes.

This makes checking if a node was imported or not through the templates a lot less elegant.

**Comment by DavidMarchant** [comment]
Ah that is a good spot

Another edge case: If a node is created with edit/modify and then imported data is merged with that file, do you want `imported` to be `true` or `false`? It could be `true` because it would have been imported eventually or it could be `false` to retain its history & the fact that a zip for that node has been imported could be discerned from the fact `lshw` and `lsblk` exist?

**Comment by ColonelPanicks** [comment]
@DavidMarchant if we then do import data then yes `imported` should be set to true I think. In terms of how we define `imported`, I feel like this is the flag for "has data from a zip file imported" which is a useful flag to have.

**Comment by DavidMarchant** [comment]
sure thing, can do, however have we considered that in that case `imported` is basically repeated information & we could simply have a helper method `imported?` that returns true if a node hash the requisite imported fields? (i.e. `lshw` and `lsblk`)

**Comment by ColonelPanicks** [comment]
Whatever works! The helper method sounds a lot more robust than a text field so if you feel that's a better solution, go for it. As long as I've got some way of determining whether or not a component is "imported" then I'm happy.
