### ISSUE TITLE
Use maps instead of location helper

### ISSUE THREAD

**Issue by ste78** [alces-software/inventoryware#95]
Currently a placeholder for @ste78 to talk to @ColonelPanicks about the subject and argue about if its actually a thing

**Comment by ColonelPanicks** [comment]
Instead of having clever helpers for mapping locations of assets, create rack assets with an attached map which can represent the rack units with each value being the asset in that location (whilst doing similar things for chassises, etc). In terms of then handling/linking data this can be done with data parsers/helpers.

**Comment by atoghill** [comment]
With #100 merged are you happy for this issue to now be closed @ColonelPanicks?

**Comment by ColonelPanicks** [comment]
Yep!
